# Generated by Django 3.2.15 on 2022-08-28 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('author', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kayak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo_url', models.URLField()),
                ('price_addition', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('map_url', models.URLField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderKayak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('kayak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kajaki_app.kayak')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kajaki_app.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='kayaks',
            field=models.ManyToManyField(through='kajaki_app.OrderKayak', to='kajaki_app.Kayak'),
        ),
        migrations.AddField(
            model_name='order',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kajaki_app.route'),
        ),
    ]
